sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t Andrelino7525/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Andrelino7525/docker-react npm run test
